WebMVCPhongMach/Controllers/DetailController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PagedList;
using WebGrease.Css.Ast.Selectors;
using WebMVCPhongMach.Models;
namespace WebMVCPhongMach.Controllers
{
    public class DetailController : Controller
    {
        private PhongMachEntities db = new PhongMachEntities();
        // GET: Detail
        public ActionResult Detail(string id)
        {
            var id_ = int.Parse(id.Split('-').Last());
            var dataNew = from data in db.tbl_new_PM
                          where data.Status_new_PM == 1 && data.ID_new_PM == id_ 
                          orderby data.ID_new_PM descending
                          select data;
            return PartialView("Detail", dataNew.ToList());
        }
    }
}

WebMVCPhongMach/Controllers/tbl_EmailController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Net.Mail;
using System.Web.Mvc;
using PagedList;
using WebMVCPhongMach.Models;

namespace WebMVCPhongMach.Controllers
{
    public class tbl_EmailController : Controller
    {
        private readonly PhongMachEntities db = new PhongMachEntities();

        // GET: tbl_Email
        public ActionResult Index()
        {
            return
                View(db.tbl_Email.Where(x => x.Email.Contains("tunguyen.it.dev@gmail.com")).ToList().ToPagedList(1, 100));
            //return View(db.tbl_Email.ToList());
        }

        // GET: tbl_Email/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tbl_Email tbl_Email = db.tbl_Email.Find(id);
            if (tbl_Email == null)
            {
                return HttpNotFound();
            }
            return View(tbl_Email);
        }

        // GET: tbl_Email/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: tbl_Email/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID_Email,Email")] tbl_Email tbl_Email)
        {
            if (ModelState.IsValid)
            {
                db.tbl_Email.Add(tbl_Email);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(tbl_Email);
        }

        // GET: tbl_Email/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tbl_Email tbl_Email = db.tbl_Email.Find(id);
            if (tbl_Email == null)
            {
                return HttpNotFound();
            }
            return View(tbl_Email);
        }

        // POST: tbl_Email/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID_Email,Email")] tbl_Email tbl_Email)
        {
            if (ModelState.IsValid)
            {
                db.Entry(tbl_Email).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(tbl_Email);
        }

        // GET: tbl_Email/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tbl_Email tbl_Email = db.tbl_Email.Find(id);
            if (tbl_Email == null)
            {
                return HttpNotFound();
            }
            return View(tbl_Email);
        }

        // POST: tbl_Email/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            tbl_Email tbl_Email = db.tbl_Email.Find(id);
            db.tbl_Email.Remove(tbl_Email);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        // [HttpPost, ActionName("Send")]
        //[ValidateAntiForgeryToken]
        public ActionResult Send(int id)
        {
            if (ModelState.IsValid)
            {
                using (var r = new StreamReader(Server.MapPath("~/Content/refeshtv.txt")))
                {
                    tbl_Email tbl_Email = db.tbl_Email.Find(id);
                    var mail = new MailMessage();
                    mail.To.Add(tbl_Email.Email);
                    mail.From = new MailAddress("tien131091@gmail.com");
                    mail.Subject = "Refresh TV vừa tải lên video";
                    string Body = r.ReadToEnd();
                    mail.Body = Body;
                    mail.IsBodyHtml = true;
                    var smtp = new SmtpClient();
                    smtp.Host = "smtp.gmail.com";
                    smtp.Port = 587;
                    smtp.UseDefaultCredentials = false;
                    smtp.Credentials = new NetworkCredential
                        ("tien131091@gmail.com", "Doilanhuthe1");
                    smtp.EnableSsl = true;
                    smtp.Send(mail);
                }
            }

            return RedirectToAction("Index");
        }


        public ActionResult SendAll()
        {
            if (ModelState.IsValid)
            {
                
                //tu23444
                //hoang84522
                List<tbl_Email> email =
                    (from nameemail in db.tbl_Email
                     where nameemail.ID_Email < 1000
                        select nameemail).ToList();

                foreach (tbl_Email namem in email)
                {
                    if (namem.Email.Contains(",")==false)
                    {
                        using (var r = new StreamReader(Server.MapPath("~/Content/refeshtv.txt")))
                        {
                            try
                            {
                                var mail = new MailMessage();
                                mail.To.Add(namem.Email);
                                mail.From = new MailAddress("tien131091@gmail.com");
                                mail.Subject = "Refresh TV vừa tải lên video";
                                string Body = r.ReadToEnd();
                                mail.Body = Body;
                                mail.IsBodyHtml = true;
                                var smtp = new SmtpClient();
                                smtp.Host = "smtp.gmail.com";
                                smtp.Port = 587;
                                smtp.UseDefaultCredentials = false;
                                smtp.Credentials = new NetworkCredential
                                    ("tien131091@gmail.com", "Doilanhuthe1");
                                smtp.EnableSsl = true;
                                smtp.Send(mail);
                            }
                            catch (Exception)
                            {
                                
                                throw;
                            }
                           
                        }
                    }
                }
            }

            return RedirectToAction("Index");
        }
        public ActionResult SendAll1()
        {
            if (ModelState.IsValid)
            {

                //tu23444
                //hoang84522
                List<tbl_Email> email =
                    (from nameemail in db.tbl_Email
                     where nameemail.ID_Email > 8000   &&   nameemail.ID_Email < 9000
                     select nameemail).ToList();

                foreach (tbl_Email namem in email)
                {
                    if (namem.Email.Contains(",") == false)
                    {
                        using (var r = new StreamReader(Server.MapPath("~/Content/refeshtv.txt")))
                        {
                            var mail = new MailMessage();
                            mail.To.Add(namem.Email);
                            mail.From = new MailAddress("refeshtv@gmail.com");
                            mail.Subject = "Refresh TV vừa tải lên video";
                            string Body = r.ReadToEnd();
                            mail.Body = Body;
                            mail.IsBodyHtml = true;
                            var smtp = new SmtpClient();
                            smtp.Host = "smtp.gmail.com";
                            smtp.Port = 587;
                            smtp.UseDefaultCredentials = false;
                            smtp.Credentials = new NetworkCredential
                                ("refeshtv@gmail.com", "Doilanhuthe1");
                            smtp.EnableSsl = true;
                            smtp.Send(mail);
                        }
                    }
                }
            }

            return RedirectToAction("Index");
        }
        public ActionResult SendAll2()
        {
            if (ModelState.IsValid)
            {

                //tu23444
                //hoang84522
                List<tbl_Email> email =
                    (from nameemail in db.tbl_Email
                     where nameemail.ID_Email > 7000 && nameemail.ID_Email < 8000
                     select nameemail).ToList();

                foreach (tbl_Email namem in email)
                {
                    if (namem.Email.Contains(",") == false)
                    {
                        using (var r = new StreamReader(Server.MapPath("~/Content/refeshtv.txt")))
                        {
                            var mail = new MailMessage();
                            mail.To.Add(namem.Email);
                            mail.From = new MailAddress("tantu1306@gmail.com");
                            mail.Subject = "Refresh TV vừa tải lên video";
                            string Body = r.ReadToEnd();
                            mail.Body = Body;
                            mail.IsBodyHtml = true;
                            var smtp = new SmtpClient();
                            smtp.Host = "smtp.gmail.com";
                            smtp.Port = 587;
                            smtp.UseDefaultCredentials = false;
                            smtp.Credentials = new NetworkCredential

WebMVCPhongMach/Views/tbl_Email/Create.cshtml
@model WebMVCPhongMach.Models.tbl_Email

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/MasterLayout.cshtml";
}

<h2>Create</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>tbl_Email</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

WebMVCPhongMach/Views/tbl_Email/Delete.cshtml
@model WebMVCPhongMach.Models.tbl_Email

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/MasterLayout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>tbl_Email</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

WebMVCPhongMach/Views/tbl_Email/Details.cshtml
@model WebMVCPhongMach.Models.tbl_Email

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/MasterLayout.cshtml";
}

<h2>Details</h2>

<div>
    <h4>tbl_Email</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.ID_Email }) |
    @Html.ActionLink("Back to List", "Index")
</p>

WebMVCPhongMach/Views/tbl_Email/Edit.cshtml
@model WebMVCPhongMach.Models.tbl_Email

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/MasterLayout.cshtml";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>tbl_Email</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ID_Email)

        <div class="form-group">
            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

WebMVCPhongMach/Views/tbl_Email/EmailResult.cshtml
@using PagedList
@using PagedList.Mvc
@using WebMVCPhongMach.Models
@model IEnumerable<tbl_Email>
@{
    Layout = null;
    PhongMachEntities db = new PhongMachEntities();
    var dataNew = (from datanew in db.tbl_Email where datanew.Email.Contains("tunguyen.it.dev@gmail.com")  select datanew).ToList().ToPagedList(1, 10);
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>EmailResult</title>
</head>
<body>
    @Html.ActionLink("SendAll", "SendAll")
    @Html.Partial("~/Views/tbl_Email/EmailResult.cshtml", dataNew)
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" />
    <link href="~/Content/dataTables.bootstrap.min.css" rel="stylesheet" />

    <script src="~/Scripts/jquery-1.12.0.min.js"></script>
    <script src="~/Scripts/jquery.dataTables.min.js"></script>
    <script src="~/Scripts/dataTables.bootstrap.min.js"></script>
    <script>
        $(document).ready(function () {
           
            $('#example1').DataTable();
        });
    </script>
</body>
</html>

WebMVCPhongMach/Views/tbl_Email/EmailResultpa.cshtml
@using MvcAjaxPager
@using PagedList.Mvc
@using IPagedList = PagedList.IPagedList
<div id="loader">
    <table id="example1" class="table table-striped table-bordered" cellspacing="0" width="100%">
        <thead>
            <tr>
                <th>ID</th>
                <th>Email</th>
                <th></th>

            </tr>
        </thead>

        <tbody>

            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.ID_Email)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Email)
                    </td>
                    <td>
                        @Html.ActionLink("Edit", "Edit", new { id = item.ID_Email }) |
                        @Html.ActionLink("Details", "Details", new { id = item.ID_Email }) |
                        @Html.ActionLink("Delete", "Delete", new { id = item.ID_Email })
                        @Html.ActionLink("Send", "Send", new { id = item.ID_Email })
                    </td>
                </tr>
            }



        </tbody>
    </table>
</div>
@Html.PagedListPager((IPagedList) Model, page => Url.Action("EmailResultpa", "tbl_Email", new { page }), PagedListRenderOptions.EnableUnobtrusiveAjaxReplacing(new AjaxOptions() { UpdateTargetId = "loader" }))

WebMVCPhongMach/Views/tbl_Email/EmailTu.cshtml
@Html.ActionLink("SendAll", "SendAll")

WebMVCPhongMach/Views/tbl_Email/Index.cshtml
@using PagedList
@using PagedList.Mvc
@model IEnumerable<WebMVCPhongMach.Models.tbl_Email>

@{
    ViewBag.Title = "Index";
   
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
@Html.ActionLink("SendAll", "SendAll")
@Html.ActionLink("SendAll1", "SendAll1")
@Html.ActionLink("SendAll2", "SendAll2")
@Html.ActionLink("SendAll3", "SendAll3")
@Html.ActionLink("SendAll4", "SendAll4")
<table class="table table-striped table-bordered table-hover" id="dataTables-example">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Email)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Email)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id = item.ID_Email }) |
                @Html.ActionLink("Details", "Details", new { id = item.ID_Email }) |
                @Html.ActionLink("Delete", "Delete", new { id = item.ID_Email })
                @Html.ActionLink("Send", "Send", new { id = item.ID_Email })
            </td>
        </tr>
    }

</table>